import type { CommunityReport } from "@/features/community-reports/types";

function minutesAgo(min: number): string {
  return new Date(Date.now() - min * 60_000).toISOString();
}

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60_000).toISOString();
}

export const COMMUNITY_REPORTS: CommunityReport[] = [
  {
    id: "report-1",
    category: "poor-lighting",
    title: "Dim stretch near the flyover underpass",
    description:
      "Streetlights have been out for over a week on the service road just before the Sector 62 flyover. Hard to spot the footpath after dark.",
    location: "Sector 62 flyover, Noida",
    severity: "medium",
    reportedAt: minutesAgo(42),
    verifiedCount: 6,
  },
  {
    id: "report-2",
    category: "harassment",
    title: "Verbal harassment reported near market entrance",
    description:
      "A group of men were reported making passing comments at women near the Sector 18 market main gate around evening hours.",
    location: "Sector 18 Market, Noida",
    severity: "high",
    reportedAt: minutesAgo(95),
    verifiedCount: 11,
  },
  {
    id: "report-3",
    category: "unsafe-area",
    title: "Isolated stretch with no shops after 9 PM",
    description:
      "The road connecting the metro station to the residential blocks empties out completely after 9 PM — no shops, no footfall.",
    location: "Botanical Garden Metro Rd, Noida",
    severity: "medium",
    reportedAt: minutesAgo(180),
    verifiedCount: 4,
  },
  {
    id: "report-4",
    category: "suspicious-activity",
    title: "Unmarked vehicle idling near college gate",
    description:
      "Same unmarked car reported idling near the JIIT back gate for three evenings in a row. Reported to campus security.",
    location: "JIIT Back Gate, Sector 62",
    severity: "high",
    reportedAt: minutesAgo(260),
    verifiedCount: 3,
  },
  {
    id: "report-5",
    category: "broken-streetlight",
    title: "Three consecutive streetlights not working",
    description:
      "Between house numbers 210–240, three streetlights in a row are non-functional, creating a long dark patch on the walkway.",
    location: "Sector 62, Block C, Noida",
    severity: "low",
    reportedAt: minutesAgo(400),
    verifiedCount: 8,
  },
  {
    id: "report-6",
    category: "poor-lighting",
    title: "Park pathway unlit after sunset",
    description: "The shortcut path through the community park has no functioning lights past 7 PM.",
    location: "Sector 78 Community Park, Noida",
    severity: "low",
    reportedAt: minutesAgo(540),
    verifiedCount: 2,
  },
  {
    id: "report-7",
    category: "unsafe-area",
    title: "Construction debris blocking footpath",
    description:
      "Ongoing construction has blocked the footpath, forcing pedestrians onto the road with fast-moving traffic and no lighting.",
    location: "Sector 61 Main Road, Noida",
    severity: "medium",
    reportedAt: minutesAgo(720),
    verifiedCount: 5,
  },
  {
    id: "report-8",
    category: "harassment",
    title: "Persistent following reported near bus stop",
    description: "A commuter reported being followed for several minutes after alighting at the bus stop.",
    location: "Sector 37 Bus Stop, Noida",
    severity: "high",
    reportedAt: minutesAgo(1020),
    verifiedCount: 9,
  },
  // ================= DELHI REPORTS (30) =================
  {
    id: "report-9",
    category: "poor-lighting",
    title: "Dim corridor in CP E-Block",
    description: "The inner corridor of CP Block E has four consecutive storefront lights broken. Extremely dark and isolated after 9:30 PM.",
    location: "Connaught Place Block E, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(12),
    verifiedCount: 8,
    lat: 28.6304,
    lng: 77.2177,
    status: "approved"
  },
  {
    id: "report-10",
    category: "suspicious-activity",
    title: "Unmarked vehicle idling in Outer Circle",
    description: "An unmarked dark SUV with tinted windows has been parking near the corner of Outer Circle. Occupants observed staring at walking commuters.",
    location: "CP Outer Circle, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(8),
    verifiedCount: 3,
    lat: 28.6322,
    lng: 77.2201,
    status: "pending"
  },
  {
    id: "report-11",
    category: "harassment",
    title: "Eve-teasing near Select Citywalk Back Lane",
    description: "A group of men frequently gather near the back exit of the mall near the auto stand, passing vulgar comments at women walking to the metro.",
    location: "Saket Mall District Back Exit, New Delhi",
    severity: "high",
    reportedAt: daysAgo(4),
    verifiedCount: 14,
    lat: 28.5244,
    lng: 77.2066,
    status: "approved"
  },
  {
    id: "report-12",
    category: "broken-streetlight",
    title: "Broken streetlights at Saket Block M",
    description: "Two streetlights near the community park corner have been non-functional for over two weeks, leaving the walkway in complete darkness.",
    location: "Block M, Saket, New Delhi",
    severity: "low",
    reportedAt: daysAgo(19),
    verifiedCount: 5,
    lat: 28.5212,
    lng: 77.2091,
    status: "approved"
  },
  {
    id: "report-13",
    category: "unsafe-area",
    title: "Isolated alley near Hauz Khas Village",
    description: "The narrow pedestrian entry corridor leading from the main park to the village is completely unmonitored and dark after hours.",
    location: "Hauz Khas Village Pedestrian Lane, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(15),
    verifiedCount: 7,
    lat: 28.5494,
    lng: 77.2001,
    status: "approved"
  },
  {
    id: "report-14",
    category: "poor-lighting",
    title: "Dimly lit pathway Hauz Khas Sector 5",
    description: "The walkway between block gates is unlit due to overgrown tree branches blocking the light poles. High risk of tripping or confrontation.",
    location: "Sector 5 Walkway, Hauz Khas, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(25),
    verifiedCount: 4,
    lat: 28.5451,
    lng: 77.1972,
    status: "approved"
  },
  {
    id: "report-15",
    category: "harassment",
    title: "Catcalling at Lajpat Nagar Central Market",
    description: "Group of shop helpers loitering near the shoe market alleyway and making inappropriate remarks at female shoppers passing by in the evening.",
    location: "Central Market Shoe Alley, New Delhi",
    severity: "high",
    reportedAt: daysAgo(2),
    verifiedCount: 19,
    lat: 28.5679,
    lng: 77.2435,
    status: "approved"
  },
  {
    id: "report-16",
    category: "broken-streetlight",
    title: "Unlit lane in Lajpat Nagar Block K",
    description: "Entire stretch of road opposite Block K gurudwara has no working streetlights. Residents forced to walk in dark.",
    location: "Block K Lane, Lajpat Nagar, New Delhi",
    severity: "low",
    reportedAt: daysAgo(32),
    verifiedCount: 3,
    lat: 28.5699,
    lng: 77.2411,
    status: "approved"
  },
  {
    id: "report-17",
    category: "suspicious-activity",
    title: "Groups loitering near Rajouri Garden Metro exit",
    description: "Three to four men frequently loiter near the exit gates of the metro station past 10 PM. Staring and following commuters.",
    location: "Rajouri Garden Metro Exit 1, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(7),
    verifiedCount: 9,
    lat: 28.6415,
    lng: 77.1248,
    status: "approved"
  },
  {
    id: "report-18",
    category: "harassment",
    title: "Stalking incident Rajouri Main Market",
    description: "A female shopper reported being followed closely for 10 minutes through the narrow lanes of the market by a suspicious individual.",
    location: "Rajouri Main Market, New Delhi",
    severity: "high",
    reportedAt: daysAgo(6),
    verifiedCount: 11,
    lat: 28.6432,
    lng: 77.1271,
    status: "approved"
  },
  {
    id: "report-19",
    category: "poor-lighting",
    title: "Unlit park lane in Rohini Sector 8",
    description: "The pedestrian walkway surrounding Sector 8 park has zero lights. Completely dark after 7:30 PM, making it unsafe for walks.",
    location: "Sector 8 Park Road, Rohini, New Delhi",
    severity: "high",
    reportedAt: daysAgo(11),
    verifiedCount: 6,
    lat: 28.7158,
    lng: 77.1137,
    status: "approved"
  },
  {
    id: "report-20",
    category: "unsafe-area",
    title: "Isolated pocket in Rohini Sector 15",
    description: "The underpass lane connecting Sector 15 and 16 is abandoned, has no working cameras, and has reports of rowdy groups.",
    location: "Sector 15 Underpass Road, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(20),
    verifiedCount: 8,
    lat: 28.7201,
    lng: 77.1112,
    status: "approved"
  },
  {
    id: "report-21",
    category: "broken-streetlight",
    title: "Broken light near Dwarka Sector 10 Metro",
    description: "The streetlights along the footpath from Sector 10 Metro towards the apartments are broken. Commuters have to use phone lights.",
    location: "Sector 10 Metro Footpath, New Delhi",
    severity: "low",
    reportedAt: daysAgo(42),
    verifiedCount: 4,
    lat: 28.5823,
    lng: 77.0500,
    status: "approved"
  },
  {
    id: "report-22",
    category: "suspicious-activity",
    title: "Suspicious bike riders Dwarka Sec 22",
    description: "Two men on a motorcycle without a license plate were seen riding slowly and circling the residential block multiple times around 9 PM.",
    location: "Sector 22 Residential Pocket, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(28),
    verifiedCount: 2,
    lat: 28.5801,
    lng: 77.0471,
    status: "pending"
  },
  {
    id: "report-23",
    category: "poor-lighting",
    title: "Janakpuri District Center Back alley",
    description: "The parking block corridor behind the office tower has no working lights. Isolated and unsafe stretch after office hours.",
    location: "District Center Block A parking, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(14),
    verifiedCount: 8,
    lat: 28.6219,
    lng: 77.0878,
    status: "approved"
  },
  {
    id: "report-24",
    category: "harassment",
    title: "Persistent catcalling Janakpuri Block C",
    description: "A resident reported multiple instances of verbal harassment from groups loitering around the local juice shop in Block C.",
    location: "Block C Crossing, Janakpuri, New Delhi",
    severity: "high",
    reportedAt: daysAgo(5),
    verifiedCount: 13,
    lat: 28.6241,
    lng: 77.0851,
    status: "approved"
  },
  {
    id: "report-25",
    category: "unsafe-area",
    title: "Gaffar Market back alleys",
    description: "The narrow internal lanes of Gaffar Market become highly isolated and completely dark after shops close. No patrols observed.",
    location: "Gaffar Market alleys, Karol Bagh, New Delhi",
    severity: "high",
    reportedAt: daysAgo(22),
    verifiedCount: 10,
    lat: 28.6514,
    lng: 77.1903,
    status: "approved"
  },
  {
    id: "report-26",
    category: "broken-streetlight",
    title: "Broken streetlight at Karol Bagh Block 23",
    description: "Three consecutive streetlights on Main Road 23 are down. Footpath is highly dark near the bus shelter.",
    location: "Karol Bagh Block 23, New Delhi",
    severity: "low",
    reportedAt: daysAgo(35),
    verifiedCount: 5,
    lat: 28.6535,
    lng: 77.1872,
    status: "approved"
  },
  {
    id: "report-27",
    category: "poor-lighting",
    title: "Dark alley in South Ex I",
    description: "The service road behind the retail showrooms is completely pitch black. Very risky for female employees leaving late.",
    location: "South Ext I Back Road, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(17),
    verifiedCount: 7,
    lat: 28.5726,
    lng: 77.2215,
    status: "approved"
  },
  {
    id: "report-28",
    category: "suspicious-activity",
    title: "Unattended bags / loiterers South Ex II",
    description: "Groups of suspicious men seen gathering near the dark park corner near South Ex II crossing regularly. Staring at pedestrians.",
    location: "South Ext II Crossing Park, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(30),
    verifiedCount: 6,
    lat: 28.5701,
    lng: 77.2235,
    status: "approved"
  },
  {
    id: "report-29",
    category: "harassment",
    title: "Verbal abuse GK-I M-Block Market",
    description: "A female resident reported being followed and verbally harassed by a group outside the coffee shop in M-Block market.",
    location: "M-Block Market, Greater Kailash I, New Delhi",
    severity: "high",
    reportedAt: daysAgo(9),
    verifiedCount: 12,
    lat: 28.5482,
    lng: 77.2343,
    status: "approved"
  },
  {
    id: "report-30",
    category: "broken-streetlight",
    title: "GK-II Main road lights down",
    description: "The streetlights along the block fence near the GK-II local market are out, creating a dark safety gap on the footpath.",
    location: "Greater Kailash II Local Market, New Delhi",
    severity: "low",
    reportedAt: daysAgo(48),
    verifiedCount: 4,
    lat: 28.5451,
    lng: 77.2372,
    status: "approved"
  },
  {
    id: "report-31",
    category: "unsafe-area",
    title: "Isolated road stretch Vasant Kunj Sec B",
    description: "The road connecting Sector B to the main mall area has zero foot traffic and no active police check post past 9 PM.",
    location: "Sector B Connect Road, Vasant Kunj, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(16),
    verifiedCount: 8,
    lat: 28.5424,
    lng: 77.1561,
    status: "approved"
  },
  {
    id: "report-32",
    category: "poor-lighting",
    title: "Pocket 3 walkway dim corridor",
    description: "Walkway lighting inside pocket 3 is non-existent. Residents have to walk through dark, heavily wooded areas inside the block.",
    location: "Vasant Kunj Pocket 3 Walk, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(24),
    verifiedCount: 6,
    lat: 28.5401,
    lng: 77.1531,
    status: "approved"
  },
  {
    id: "report-33",
    category: "suspicious-activity",
    title: "Rowdy crowd near NSP back lane",
    description: "Group of men seen drinking openly inside cars parked in the isolated lane behind the metro station after dark.",
    location: "Netaji Subhash Place back parking, New Delhi",
    severity: "high",
    reportedAt: daysAgo(13),
    verifiedCount: 9,
    lat: 28.6990,
    lng: 77.1204,
    status: "approved"
  },
  {
    id: "report-34",
    category: "broken-streetlight",
    title: "Unlit block lane Pitampura Block JD",
    description: "Two streetlights have been completely broken for a month inside Block JD lane. Very dark around the community gates.",
    location: "Pitampura Block JD, New Delhi",
    severity: "low",
    reportedAt: daysAgo(50),
    verifiedCount: 5,
    lat: 28.6961,
    lng: 77.1182,
    status: "approved"
  },
  {
    id: "report-35",
    category: "poor-lighting",
    title: "Civil Lines Underpass dark stretch",
    description: "The pedestrian corridor inside the Civil Lines underpass is completely unlit. Extremely isolated and high risk.",
    location: "Civil Lines Underpass walk, New Delhi",
    severity: "high",
    reportedAt: daysAgo(10),
    verifiedCount: 11,
    lat: 28.6814,
    lng: 77.2224,
    status: "approved"
  },
  {
    id: "report-36",
    category: "unsafe-area",
    title: "Isolated lane in Chandni Chowk",
    description: "The narrow alley of Katra Neel has no security cameras, very poor lighting, and becomes completely deserted after 8 PM.",
    location: "Katra Neel Alley, Chandni Chowk, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(23),
    verifiedCount: 6,
    lat: 28.6562,
    lng: 77.2300,
    status: "approved"
  },
  {
    id: "report-37",
    category: "harassment",
    title: "Eve-teasing Defence Colony Flyover",
    description: "Two men riding an electric scooter have been repeatedly catcalling women crossing the pedestrian stairs of the flyover in the evenings.",
    location: "Defence Colony Flyover Pedestrian Steps, New Delhi",
    severity: "high",
    reportedAt: daysAgo(3),
    verifiedCount: 15,
    lat: 28.5727,
    lng: 77.2331,
    status: "approved"
  },
  {
    id: "report-38",
    category: "poor-lighting",
    title: "Mayur Vihar Ph I Pocket 1 walkway",
    description: "Dim lights under heavy tree canopy on the main block walkway. Very difficult to see ahead after sunset.",
    location: "Mayur Vihar Pocket 1 Walk, New Delhi",
    severity: "medium",
    reportedAt: daysAgo(18),
    verifiedCount: 8,
    lat: 28.6040,
    lng: 77.2934,
    status: "approved"
  },

  // ================= GURGAON REPORTS (30) =================
  {
    id: "report-39",
    category: "poor-lighting",
    title: "Cyber City Building 10 back road",
    description: "The service road behind Building 10 is very poorly lit. The corporate shuttle stops far away, forcing employees to walk in the dark.",
    location: "Cyber City Building 10 Back Road, Gurgaon",
    severity: "low",
    reportedAt: daysAgo(20),
    verifiedCount: 4,
    lat: 28.4950,
    lng: 77.0896,
    status: "approved"
  },
  {
    id: "report-40",
    category: "suspicious-activity",
    title: "Suspicious groups near Cyber Hub periphery",
    description: "Groups of men seen loitering around the dark parking exits of Cyber Hub near the highway. Staring at solo female travelers waiting for cabs.",
    location: "Cyber Hub Highway Exit, Gurgaon",
    severity: "medium",
    reportedAt: daysAgo(12),
    verifiedCount: 7,
    lat: 28.4971,
    lng: 77.0872,
    status: "approved"
  },
  {
    id: "report-41",
    category: "harassment",
    title: "Persistent catcalling near Sector 53-54 Metro",
    description: "Commuters reporting a group of boys standing near the stairs of the Sector 53-54 Rapid Metro station who pass comments when women exit.",
    location: "Sector 53-54 Rapid Metro Exit, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(6),
    verifiedCount: 12,
    lat: 28.4419,
    lng: 77.0984,
    status: "approved"
  },
  {
    id: "report-42",
    category: "broken-streetlight",
    title: "Broken streetlights Golf Course Block B",
    description: "Multiple streetlights are completely out from Block B crossing to the metro corridor, creating a dark walkway patch.",
    location: "Golf Course Road Block B, Gurgaon",
    severity: "low",
    reportedAt: daysAgo(38),
    verifiedCount: 6,
    lat: 28.4452,
    lng: 77.0951,
    status: "approved"
  },
  {
    id: "report-43",
    category: "unsafe-area",
    title: "Isolated road stretch on GC Extension Rd",
    description: "The road connecting Sector 61 to Sector 62 is heavily isolated, has no active police patrols, and has very sparse vehicle movement after 10 PM.",
    location: "Sector 61 Connector Road, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(15),
    verifiedCount: 9,
    lat: 28.4062,
    lng: 77.0924,
    status: "approved"
  },
  {
    id: "report-44",
    category: "poor-lighting",
    title: "DLF Phase 1 Ridge Road dark walk",
    description: "The Ridge Road stretch bordering DLF Phase 1 has zero working lights. Highly isolated and heavily forested on one side.",
    location: "DLF Phase 1 Ridge Road, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(11),
    verifiedCount: 11,
    lat: 28.4719,
    lng: 77.0974,
    status: "approved"
  },
  {
    id: "report-45",
    category: "harassment",
    title: "Eve-teasing DLF Phase 2 Block L",
    description: "A female resident reported being followed for several meters by a man on foot down the Block L lane around 9 PM.",
    location: "Block L lane, DLF Phase 2, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(8),
    verifiedCount: 16,
    lat: 28.4745,
    lng: 77.0942,
    status: "approved"
  },
  {
    id: "report-46",
    category: "suspicious-activity",
    title: "U-Block loiterers and rowdy crowds",
    description: "Multiple residents have reported groups of rowdy men drinking openly on the street corner near the local grocery shop after 10 PM.",
    location: "U-Block Sector 24, DLF Phase 3, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(5),
    verifiedCount: 22,
    lat: 28.4799,
    lng: 77.0912,
    status: "approved"
  },
  {
    id: "report-47",
    category: "broken-streetlight",
    title: "Galleria back lane lights broken",
    description: "Two light poles behind the Galleria market complex are non-functional, leaving the path to the parking lot in complete darkness.",
    location: "Galleria Market Back parking, Gurgaon",
    severity: "low",
    reportedAt: daysAgo(29),
    verifiedCount: 5,
    lat: 28.4604,
    lng: 77.0782,
    status: "approved"
  },
  {
    id: "report-48",
    category: "poor-lighting",
    title: "Dim walkway DLF Phase 5 Horizon Center",
    description: "Path connecting the office complex to the metro walkway is very dim under the trees. Needs additional lighting fixtures.",
    location: "Horizon Center Walkway, Gurgaon",
    severity: "low",
    reportedAt: daysAgo(45),
    verifiedCount: 4,
    lat: 28.4551,
    lng: 77.0812,
    status: "approved"
  },
  {
    id: "report-49",
    category: "unsafe-area",
    title: "Leisure Valley park isolated corridor",
    description: "The walking track along the back wall of Leisure Valley park is completely dark and has no security guards visible past sunset.",
    location: "Leisure Valley Park Walk, Sector 29, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(16),
    verifiedCount: 13,
    lat: 28.4682,
    lng: 77.0637,
    status: "approved"
  },
  {
    id: "report-50",
    category: "harassment",
    title: "Catcalling at Sector 29 Market",
    description: "Commuters reported a group of intoxicated men passing vulgar remarks at women waiting near the taxi pickup stand outside the food court.",
    location: "Sector 29 Market Cab Stand, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(4),
    verifiedCount: 18,
    lat: 28.4651,
    lng: 77.0611,
    status: "approved"
  },
  {
    id: "report-51",
    category: "broken-streetlight",
    title: "Sector 45 Block C streetlights down",
    description: "Three consecutive streetlights inside the Block C residential lane are broken. High risk for late-night walking.",
    location: "Sector 45 Block C, Gurgaon",
    severity: "low",
    reportedAt: daysAgo(31),
    verifiedCount: 6,
    lat: 28.4485,
    lng: 77.0682,
    status: "approved"
  },
  {
    id: "report-52",
    category: "suspicious-activity",
    title: "Suspicious bike riders Sector 56",
    description: "Two boys riding a motorcycle without helmets were observed circling the Huda Market parking lot slowly and staring at female shoppers.",
    location: "Huda Market parking lot, Sector 56, Gurgaon",
    severity: "medium",
    reportedAt: daysAgo(9),
    verifiedCount: 8,
    lat: 28.4239,
    lng: 77.1002,
    status: "approved"
  },
  {
    id: "report-53",
    category: "poor-lighting",
    title: "Dim street crossing Sector 57",
    description: "The T-point crossing near the sector entrance is unlit. The single streetlight on the pole has been fused for over a month.",
    location: "Sector 57 T-Point, Gurgaon",
    severity: "medium",
    reportedAt: daysAgo(24),
    verifiedCount: 7,
    lat: 28.4243,
    lng: 77.0792,
    status: "approved"
  },
  {
    id: "report-54",
    category: "unsafe-area",
    title: "Isolated construction zone Sector 65",
    description: "The road running parallel to the new commercial complex is heavily isolated and unlit, with construction debris blocking the footpath.",
    location: "Sector 65 Main Road, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(22),
    verifiedCount: 10,
    lat: 28.3976,
    lng: 77.0714,
    status: "approved"
  },
  {
    id: "report-55",
    category: "broken-streetlight",
    title: "Sector 67 Block A lights broken",
    description: "Lights are down along the entire perimeter path of Block A society. Footpath is highly dark near the park entrance.",
    location: "Sector 67 Block A, Gurgaon",
    severity: "low",
    reportedAt: daysAgo(55),
    verifiedCount: 4,
    lat: 28.3912,
    lng: 77.0722,
    status: "approved"
  },
  {
    id: "report-56",
    category: "poor-lighting",
    title: "Dark corridor Sector 70",
    description: "Service lane near the high-rise societies is completely unlit. Extremely dark stretch that is unsafe for walking from the bus stop.",
    location: "Sector 70 Service Road, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(14),
    verifiedCount: 12,
    lat: 28.3919,
    lng: 77.0337,
    status: "approved"
  },
  {
    id: "report-57",
    category: "suspicious-activity",
    title: "Unmarked bike circling Sector 83",
    description: "Residents observed a motorcycle without a license plate parked near the society gate. Riders left when security guards approached.",
    location: "Sector 83 society gate, Gurgaon",
    severity: "medium",
    reportedAt: daysAgo(17),
    verifiedCount: 5,
    lat: 28.3957,
    lng: 76.9691,
    status: "approved"
  },
  {
    id: "report-58",
    category: "unsafe-area",
    title: "Sector 90 construction boundary road",
    description: "The boundary road along the large vacant land area has zero lighting and no foot traffic, making it highly isolated in the evenings.",
    location: "Sector 90 Boundary road, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(26),
    verifiedCount: 8,
    lat: 28.4022,
    lng: 76.9463,
    status: "approved"
  },
  {
    id: "report-59",
    category: "harassment",
    title: "Catcalling near Subhash Chowk",
    description: "A female pedestrian reported a group of boys standing near the local tea stall who pass comments when women cross the road.",
    location: "Subhash Chowk Crossing, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(7),
    verifiedCount: 11,
    lat: 28.4021,
    lng: 77.0396,
    status: "approved"
  },
  {
    id: "report-60",
    category: "broken-streetlight",
    title: "Unlit bus shelter near Omaxe Mall",
    description: "The streetlight pole next to the bus shelter is down. Commuters have to wait for buses in pitch darkness.",
    location: "Sohna Road bus stand, Gurgaon",
    severity: "low",
    reportedAt: daysAgo(40),
    verifiedCount: 5,
    lat: 28.4042,
    lng: 77.0361,
    status: "approved"
  },
  {
    id: "report-61",
    category: "harassment",
    title: "Eve-teasing MG Road Metro pillars",
    description: "Group of boys gather near metro pillar 122 under the bridge, staring and catcalling at women walking to the malls.",
    location: "MG Road Metro Pillar 122, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(3),
    verifiedCount: 15,
    lat: 28.4798,
    lng: 77.0803,
    status: "approved"
  },
  {
    id: "report-62",
    category: "suspicious-activity",
    title: "Rowdy crowds MG Road Mall corridor",
    description: "Open alcohol drinking inside cars parked on the service road near the malls, leading to rowdy and unsafe behavior in the evening.",
    location: "MG Road Mall Mile, Gurgaon",
    severity: "medium",
    reportedAt: daysAgo(10),
    verifiedCount: 9,
    lat: 28.4772,
    lng: 77.0781,
    status: "approved"
  },
  {
    id: "report-63",
    category: "poor-lighting",
    title: "Udyog Vihar Ph IV unlit corridor",
    description: "The corporate lane behind the main IT park has no working streetlights, making it dark and dangerous for employees leaving late shifts.",
    location: "Udyog Vihar Phase IV, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(13),
    verifiedCount: 14,
    lat: 28.5029,
    lng: 77.0772,
    status: "approved"
  },
  {
    id: "report-64",
    category: "unsafe-area",
    title: "Isolated road Udyog Vihar Ph V",
    description: "The road connecting the main road to the expressway becomes completely empty and unpatrolled after office shuttle hours.",
    location: "Udyog Vihar Phase V Connect, Gurgaon",
    severity: "medium",
    reportedAt: daysAgo(21),
    verifiedCount: 7,
    lat: 28.5001,
    lng: 77.0751,
    status: "approved"
  },
  {
    id: "report-65",
    category: "broken-streetlight",
    title: "Broken lights Sushant Lok I Block C",
    description: "Two streetlights inside Block C crossing have been down for a month, leaving the residential lane in complete darkness.",
    location: "Block C Crossing, Sushant Lok I, Gurgaon",
    severity: "low",
    reportedAt: daysAgo(49),
    verifiedCount: 4,
    lat: 28.4604,
    lng: 77.0782,
    status: "approved"
  },
  {
    id: "report-66",
    category: "poor-lighting",
    title: "Nirvana Country main walkway dim corridor",
    description: "walkway lighting along the main road is blocked by thick tree branches, leaving the pedestrian path unlit.",
    location: "Nirvana Country Main Walk, Gurgaon",
    severity: "low",
    reportedAt: daysAgo(30),
    verifiedCount: 5,
    lat: 28.4116,
    lng: 77.0626,
    status: "approved"
  },
  {
    id: "report-67",
    category: "suspicious-activity",
    title: "Suspicious car idling Palam Vihar",
    description: "An unmarked car was seen parking in the same spot in Block G for three nights in a row, with occupants loitering on the sidewalk.",
    location: "Block G, Palam Vihar, Gurgaon",
    severity: "medium",
    reportedAt: daysAgo(18),
    verifiedCount: 8,
    lat: 28.5034,
    lng: 77.0454,
    status: "approved"
  },
  {
    id: "report-68",
    category: "unsafe-area",
    title: "Isolated road New Gurgaon Sec 102",
    description: "The main road heading towards the sector apartments has zero pedestrian traffic and no streetlights, making it highly isolated.",
    location: "Sector 102 main road, Gurgaon",
    severity: "high",
    reportedAt: daysAgo(27),
    verifiedCount: 9,
    lat: 28.4087,
    lng: 76.9531,
    status: "approved"
  },
];
